version: '3.8'

services:
  web:
    build: .
    ports:
      - "5200:5000"
    volumes:
      - ./app:/app
      - ./Desktop/Input_Tasks:/Desktop/Input_Tasks
      - ./Desktop/Reports:/Desktop/Reports
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/taskdb
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
