services:
  web:
    build: .
    ports:
      - "10.50.57.107:5200:5000"
    volumes:
      - ./app:/app
      - ./data:/data
      - ./Desktop/Input_Tasks:/Desktop/Input_Tasks
      - ./Desktop/Reports:/Desktop/Reports
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - YANDEX_DISK_TOKEN=${YANDEX_DISK_TOKEN:-}
      - YANDEX_DISK_FOLDER=${YANDEX_DISK_FOLDER:-/SmartControl/Отчёты}
    restart: unless-stopped
